In [1]:
import numpy as np

# 1.创建

In [2]:
# 存储多位同学的成绩

score = np.array([[80, 89, 86, 67, 79], [78, 97, 89, 67, 81],
                  [90, 94, 78, 67, 74], [91, 91, 90, 67, 69],
                  [76, 87, 75, 67, 86], [70, 79, 84, 67, 84],
                  [94, 92, 93, 67, 64], [86, 85, 83, 67, 80]])

In [3]:
score

array([[80, 89, 86, 67, 79],
       [78, 97, 89, 67, 81],
       [90, 94, 78, 67, 74],
       [91, 91, 90, 67, 69],
       [76, 87, 75, 67, 86],
       [70, 79, 84, 67, 84],
       [94, 92, 93, 67, 64],
       [86, 85, 83, 67, 80]])

# 2.效率对比

In [4]:
import random
import time
import numpy as np

a = []
for i in range(100000000):
    a.append(random.random())

# 通过%time魔法方法, 查看当前行的代码运行一次所花费的时间
%time sum1=sum(a)

b = np.array(a)

%time sum2=np.sum(b)

Wall time: 362 ms
Wall time: 99.7 ms


# 3.ndarray的属性

In [5]:
score.shape

(8, 5)

In [6]:
score.ndim

2

In [7]:
score.size

40

In [8]:
score.itemsize

4

In [9]:
score.dtype

dtype('int32')

# 4.ndarray的形状

In [10]:
a = np.array([1,2,3,])

In [11]:
a

array([1, 2, 3])

In [12]:
b = np.array([[1,2,3,],[2,3,4]])

In [13]:
b

array([[1, 2, 3],
       [2, 3, 4]])

In [14]:
c = np.array([[[
    1,
    2,
    3,
], [2, 3, 4]], [[
    3,
    4,
    5,
], [4, 5, 6]]])

In [15]:
c

array([[[1, 2, 3],
        [2, 3, 4]],

       [[3, 4, 5],
        [4, 5, 6]]])

In [16]:
a.shape

(3,)

In [17]:
b.shape

(2, 3)

In [18]:
c.shape

(2, 2, 3)

In [ ]:
a.dtype

# 5.ndarray的类型

In [19]:
d = np.array([
    1,
    2,
    3,
], dtype=np.float32)

In [20]:
d

array([ 1.,  2.,  3.], dtype=float32)

In [21]:
e = np.array(["I", "love", "python"], dtype=np.string_)

In [22]:
e

array([b'I', b'love', b'python'],
      dtype='|S6')