In [2]:
import numpy as np

# 1.逻辑运算

In [3]:
stock_change = np.random.normal(0,1,(8,10))

In [4]:
stock_change

array([[ 0.07943666,  0.29210063,  2.01681976, -0.19859046,  1.44068777,
        -0.4104087 ,  1.07550713, -1.00396564, -0.26212182, -0.99262209],
       [ 0.11109803,  1.04478979,  0.36006157, -0.79759231, -0.06493237,
        -0.35959267,  1.01732117,  0.54134735, -1.68048312,  0.24069476],
       [ 1.45293753,  0.57812397,  0.62375919,  0.90053998, -0.75836843,
        -1.41588355,  0.38188096,  0.70766587,  0.92791106,  0.40957562],
       [ 0.0951799 ,  0.92517038,  0.76208371, -0.12069769, -1.22134476,
         1.40903434, -0.01028014,  0.2616652 ,  0.74562507, -0.44151674],
       [ 0.30444452,  1.48231564, -0.1317338 ,  0.90637964,  0.43447732,
         1.51937914,  0.60450989,  1.22453861,  0.55622373, -2.09710398],
       [-0.17712551,  0.83966351, -0.98441576,  0.81234286,  0.06599311,
         0.6930254 , -0.69390989,  0.09106625,  0.18939176,  0.38661236],
       [ 1.17595097,  0.74203224,  0.480381  , -0.58632663, -0.75306909,
        -0.26363067, -1.65164022, -1.69411665

In [5]:
stock_c = stock_change[0:5,0:5]

In [6]:
stock_c > 1

array([[False, False,  True, False,  True],
       [False,  True, False, False, False],
       [ True, False, False, False, False],
       [False, False, False, False, False],
       [False,  True, False, False, False]], dtype=bool)

In [7]:
stock_c[stock_c > 1] = 2

In [8]:
stock_c

array([[ 0.07943666,  0.29210063,  2.        , -0.19859046,  2.        ],
       [ 0.11109803,  2.        ,  0.36006157, -0.79759231, -0.06493237],
       [ 2.        ,  0.57812397,  0.62375919,  0.90053998, -0.75836843],
       [ 0.0951799 ,  0.92517038,  0.76208371, -0.12069769, -1.22134476],
       [ 0.30444452,  2.        , -0.1317338 ,  0.90637964,  0.43447732]])

In [9]:
test_a = [1,2,3]

In [11]:
#test_a > 2

# 2.通用判断函数

In [12]:
stock_d = stock_change[0:2,0:5]

In [13]:
stock_d

array([[ 0.07943666,  0.29210063,  2.        , -0.19859046,  2.        ],
       [ 0.11109803,  2.        ,  0.36006157, -0.79759231, -0.06493237]])

In [14]:
np.all(stock_d > 0)

False

In [15]:
np.any(stock_d > 0)

True

# 3.三元运算符

In [16]:
np.where(stock_d > 0, 1, 0)

array([[1, 1, 1, 0, 1],
       [1, 1, 1, 0, 0]])

In [17]:
np.where(np.logical_and(stock_d > -0.5, stock_d < 0.5), 1, 0)

array([[1, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]])

In [18]:
np.where(np.logical_or(stock_d > 0, stock_d < -1), 2, 0)

array([[2, 2, 2, 0, 2],
       [2, 2, 2, 0, 0]])

# 4.统计运算符

In [19]:
stock_change = np.random.normal(0,1,(4,4))

In [20]:
stock_change

array([[ 1.00709658,  0.1132196 ,  2.13010134,  0.11252039],
       [ 0.52402921, -0.09933238,  0.20328806,  0.35553737],
       [ 0.45494675,  0.5004886 ,  1.38159612,  1.03309709],
       [ 0.50077969,  1.21929525, -0.17777089,  0.17708804]])

In [21]:
stock_change.max()

2.1301013413195573

In [22]:
stock_change.max(axis=0)

array([ 1.00709658,  1.21929525,  2.13010134,  1.03309709])

In [23]:
stock_change.max(axis=1)

array([ 2.13010134,  0.52402921,  1.38159612,  1.21929525])

In [24]:
stock_change.argmax( )

2

In [25]:
stock_change.argmax(axis=0)

array([0, 3, 0, 2], dtype=int64)

In [26]:
stock_change.argmax(axis=1)

array([2, 0, 2, 1], dtype=int64)